{{- if .Values.serviceAccount.create -}}
#
# KUBERNETES SERVICE ACCOUNT
# Purpose: Provides identity for pods to interact with Kubernetes API and other services
# Renders: When serviceAccount.create=true
#
# What it does:
# - Assigns identity to pods (used for RBAC authorization)
# - Enables pod authentication to Kubernetes API server
# - Works with Istio for workload identity and mTLS
# - Can be bound to Roles/ClusterRoles for API access
#
# Key concepts:
# - Pods reference this ServiceAccount in spec.serviceAccountName
# - Automatically mounted token at /var/run/secrets/kubernetes.io/serviceaccount/
# - Used as identity in PeerAuthentication and AuthorizationPolicy
# - Annotations can configure cloud IAM (AWS IRSA, GCP Workload Identity)
#
# Istio Integration:
# - ServiceAccount becomes the workload identity (SPIFFE ID)
# - Format: cluster.local/ns/<namespace>/sa/<serviceaccount-name>
# - Used in AuthorizationPolicy rules for access control
# - Certificate identity for mTLS connections
#
# Best practices:
# - Create dedicated ServiceAccount per application
# - Grant minimal RBAC permissions (principle of least privilege)
# - Use annotations for cloud IAM bindings (avoid static credentials)
#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app-template.serviceAccountName" . }}
  labels:
    {{- include "app-template.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  # Annotations for cloud IAM bindings (AWS IRSA, GCP Workload Identity, etc.)
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
